services:

  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: password
      POSTGRES_DB: scheduler
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: ./api
    volumes:
      - ./api:/app
      - /app/node_modules
    ports:
      - "3006:3002"
    environment:
      DATABASE_URL: "postgresql://app:password@db:5432/scheduler"
    depends_on:
      - db

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5176:5174"
    command: sh -c "npm install && npm run dev"

volumes:
  postgres_data: