services:
  api:
    build: ./api
    volumes:
      - ./api:/app
      - /app/node_modules
    ports:
      - "3006:3002"
    environment:
      DATABASE_URL: "postgresql://scheduler_app:scheduler_local_pw@shared-postgres:5432/scheduler_local"
    networks:
      - default
      - shared_net

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5176:5176"
    command: sh -c "npm install && npm run dev"
    networks:
      - default

networks:
  shared_net:
    external: true
